### model
model_name_or_path: /home/kas/kas_workspace/model/Reward/Qwen3-4B
trust_remote_code: true

### method
stage: rm
do_train: true
finetuning_type: full
deepspeed: /home/kas/kas_workspace/share/chenkai/playground/task/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset_dir: /home/kas/kas_workspace/share/chenkai/playground/dataset/
dataset: infinity_reward
template: qwen3
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
#max_samples: 1000  #test demo

### output
output_dir: /home/kas/kas_workspace/output/Qwen3_Reward_Model_4B_ft_0703
logging_steps: 1
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
flash_attn: fa2
